# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('email', models.CharField(max_length=300)),
                ('passwd', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('num_partida', models.IntegerField()),
                ('date_creation', models.DateTimeField()),
                ('date_start', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('status', models.CharField(default=b'INACTIVA', max_length=20)),
                ('experiment', models.CharField(max_length=100, null=True)),
                ('num_rondes', models.IntegerField(null=True)),
                ('ronda_actual', models.IntegerField(null=True)),
                ('data_fi_ronda', models.DateTimeField(null=True)),
                ('usuaris_registrats', models.IntegerField(default=0)),
                ('control_intervention', models.CharField(default=b'NONE', max_length=10)),
                ('control_wealth', models.CharField(default=b'EQUAL', max_length=10)),
                ('comentari', models.CharField(max_length=100, null=True)),
                ('goal_achieved', models.BooleanField(default=False)),
                ('total_contributed', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('num_ronda', models.IntegerField()),
                ('bucket_inici_ronda', models.FloatField(null=True)),
                ('bucket_final_ronda', models.FloatField(null=True)),
                ('temps_inici_ronda', models.DateTimeField(null=True)),
                ('temps_final_ronda', models.DateTimeField(null=True)),
                ('calculada', models.BooleanField(default=False)),
                ('rented', models.BooleanField(default=False)),
                ('increment', models.FloatField(null=True)),
                ('partida', models.ForeignKey(to='game.Partida')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_robot', models.BooleanField(default=False)),
                ('nickname', models.CharField(default=b'', max_length=100)),
                ('consent', models.BooleanField(default=False)),
                ('socio_pr1', models.CharField(default=b'', max_length=2)),
                ('socio_pr2', models.CharField(default=b'', max_length=2)),
                ('socio_pr3', models.CharField(default=b'', max_length=10)),
                ('socio_pr4', models.CharField(default=b'', max_length=2)),
                ('socio_pr5', models.CharField(default=b'', max_length=2)),
                ('socio_pr6', models.CharField(default=b'', max_length=2)),
                ('socio_pr7', models.CharField(default=b'', max_length=2)),
                ('frame_pr1', models.CharField(default=b'', max_length=2)),
                ('frame_pr2', models.CharField(default=b'', max_length=2)),
                ('frame_pr3', models.CharField(default=b'', max_length=2)),
                ('frame_pr4', models.CharField(default=b'', max_length=2)),
                ('frame_pr5', models.CharField(default=b'', max_length=2)),
                ('frame_pr6', models.CharField(default=b'', max_length=2)),
                ('verification_pr1', models.CharField(default=b'', max_length=100)),
                ('verification_pr2', models.CharField(default=b'', max_length=100)),
                ('verification_pr3', models.CharField(default=b'', max_length=100)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('enquesta_final_pr1', models.CharField(default=b'', max_length=100)),
                ('enquesta_final_pr2', models.CharField(default=b'', max_length=100)),
                ('enquesta_final_pr3', models.CharField(default=b'', max_length=100)),
                ('enquesta_final_pr4', models.CharField(default=b'', max_length=100)),
                ('enquesta_final_pr5', models.CharField(default=b'', max_length=100)),
                ('enquesta_final_pr6', models.CharField(default=b'', max_length=100)),
                ('enquesta_final_pr7', models.CharField(default=b'', max_length=100)),
                ('enquesta_final_pr8', models.CharField(default=b'', max_length=100)),
                ('enquesta_final_pr9', models.CharField(default=b'', max_length=100)),
                ('enquesta_final_pr10', models.CharField(default=b'', max_length=100)),
                ('enquesta_final_pr11', models.CharField(default=b'', max_length=1000)),
                ('status', models.CharField(default=b'', max_length=100)),
                ('num_jugador', models.IntegerField(null=True)),
                ('date_tutorial', models.DateTimeField(null=True)),
                ('date_register', models.DateTimeField(null=True)),
                ('date_creation', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('acabat', models.BooleanField(default=False)),
                ('num_seleccions', models.IntegerField(default=0)),
                ('bots', models.IntegerField(default=0)),
                ('endowment_initial', models.FloatField(default=0, null=True)),
                ('endowment_current', models.FloatField(default=0, null=True)),
                ('endowment_final', models.FloatField(default=0, null=True)),
                ('expenses', models.FloatField(default=0, null=True)),
                ('tickets', models.IntegerField(default=0, null=True)),
                ('house', models.BooleanField(default=False)),
                ('house_price', models.FloatField(null=True)),
                ('comment', models.CharField(default=b'', max_length=1000)),
                ('partida', models.ForeignKey(to='game.Partida', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRonda',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ha_seleccionat', models.BooleanField(default=False)),
                ('seleccio', models.IntegerField(null=True)),
                ('temps_seleccio', models.DateTimeField(null=True)),
                ('endowment_variation', models.FloatField(default=0, null=True)),
                ('ronda', models.ForeignKey(to='game.Ronda')),
                ('user', models.ForeignKey(to='game.User', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ronda',
            name='user',
            field=models.ForeignKey(to='game.User', null=True),
        ),
    ]
